name: Reusable Deployment Workflow

on:
    workflow_call:
        inputs:
            environment:
                description: 'Target environment for deployment'
                required: true
                type: string
        secrets:
            aws-role-arn:
                description: 'AWS IAM role ARN to assume for deployment'
                required: true
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              continue-on-error: true
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.aws-role-arn }}
                  aws-region: ap-southeast-2

            - name: Deploy to ${{ inputs.environment }}
              run: make deploy ENV=${{ inputs.environment }}
